micronaut:
  application:
    name: transactions
---
micronaut:
  server:
    cors:
      enabled: true
  router:
    static-resources:
      default:
        enabled: true
        mapping: /**
        paths: classpath:public
